package consts

const (
	MsgDsUriMustBeFilled = "ds URI must be filled"
	MsgDsRoundFailed     = "ds round failed"
	// MsgDsInitRoundFailed       = "ds init round failed"
	// MsgDsCompleteRoundFailed   = "ds complete round failed"
	MsgDsComplexInitFailed     = "ds complex round init failed"
	MsgDsComplexBetFailed      = "ds complex round bet failed"
	MsgDsComplexWinFailed      = "ds complex round win failed"
	MsgDsComplexCompleteFailed = "ds complex round complete failed"
	MsgDsRoundNextFailed       = "ds round next failed"
	MsgDsGetRoundStateFailed   = "ds get round state failed"
	MsgDsPutSessionStateFailed = "ds put session state failed"
	MsgDsGetSessionStateFailed = "ds get session state failed"
	MsgDsPutGamePrefsFailed    = "ds put game prefs failed"
	MsgDsGetGamePrefsFailed    = "ds get game prefs failed"
	MsgDsPutPlayerPrefsFailed  = "ds put player prefs failed"
	MsgDsGetPlayerPrefsFailed  = "ds get player prefs failed"
	MsgDsInvalidStatus         = "ds invalid HTTP status %d from API call"

	DefaultContentType   = "application/json"
	DsRoundURI           = "/v1/round"
	DsComplexInitURI     = "/v1/complex-round-init"
	DsComplexBetURI      = "/v1/complex-round-bet"
	DsComplexWinURI      = "/v1/complex-round-win"
	DsComplexCompleteURI = "/v1/complex-round-complete"
	DsRoundInitURI       = "/v1/init-round"
	DsRoundCompleteURI   = "/v1/complete-round"
	DsRoundNextURI       = "/v1/round/next"
	DsRoundStateURI      = "/v1/round-state"
	DsSessionStateURI    = "/v1/session-state"
	DsGameStateURI       = "/v1/player-game-state"
	DsPlayerStateURI     = "/v1/player-global-state"
)
