// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CcbFlagsResponse Get ChaCha Bomb flags.
//
// Response for retrieving the symbol flags for ChaCha Bomb for a bet amount.
//
// swagger:model CcbFlagsResponse
type CcbFlagsResponse struct {

	// Symbol flags.
	// Example: [0,1,0,1,0,1,0,1,1,1,0,1,1,0]
	// Required: true
	Flags []int8 `json:"flags"`

	// Indicates if the request succeeded.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
