// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GameInfoResponse Get game details & stored preferences.
//
// Response for retrieving the game specific details and player/game preferences.
//
// swagger:model GameInfoResponse
type GameInfoResponse struct {

	// Details of the game.
	// Example: {"initial":[6,2,8,4,8,9,3,2,5,7,2,5,9,5,3]}
	// Required: true
	GameData interface{} `json:"gameData"`

	// Player/game preferences.
	// Example: {"locale":"it","music":0}
	Preferences interface{} `json:"preferences,omitempty"`

	// Indicates if the request succeeded.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
