// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PingResponse Health check response.
//
// Response for successful health check.
//
// swagger:model PingResponse
type PingResponse struct {

	// Indicates if the service is healthy.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
