// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PluralsResponse Get plural strings response.
//
// Response for retrieving the plural strings.
//
// swagger:model PluralsResponse
type PluralsResponse struct {

	// Plural translations (same order as requested).
	// Required: true
	Strings []string `json:"strings"`

	// Indicates if the request was successful.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
