// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PluralsRequest Get plural strings request.
//
// Request for retrieving plural strings.
//
// swagger:model PluralsRequest
type PluralsRequest struct {

	// Device identifier (1=mobile, 2=desktop).
	// Example: 1
	Device int8 `json:"device,omitempty"`

	// Locale for the plural strings.
	// Example: en-GB
	// Required: true
	Locale string `json:"locale"`

	// Plural string requests.
	// Required: true
	Requests []PluralsRequestRequestsItems0 `json:"requests"`
}
type PluralsRequestRequestsItems0 struct {

	// Code of the plural string.
	// Example: won-amount-spins
	// Required: true
	Code string `json:"code"`

	// Parameters for the plural string.
	// Example: {spins:8,amount:100.12,multiplier:10}
	// Required: true
	Params interface{} `json:"params"`
}
