// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PreferencesResponse Change preferences response.
//
// Response for successfully changing player/game preferences.
//
// swagger:model PreferencesResponse
type PreferencesResponse struct {

	// Indicates if the request was successful.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
