// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PreferencesRequest Store preferences request.
//
// Request for storing player/game preferences.
//
// swagger:model PreferencesRequest
type PreferencesRequest struct {

	// Game bet size in cents.
	// Example: 100
	Bet *int64 `json:"bet,omitempty"`

	// Game effects volume/toggle.
	// Example: 100
	Effects *int8 `json:"effects,omitempty"`

	// Player locale.
	// Example: it
	Locale *string `json:"locale,omitempty"`

	// Game music volume/toggle.
	// Example: 100
	Music *int8 `json:"music,omitempty"`

	// Player session ID.
	// Example: bot9897cc03f5d7b43923a73bfaffc2d7dd43
	// Required: true
	SessionID string `json:"sessionId"`

	// Overall sound volume.
	// Example: 100
	Volume *int8 `json:"volume,omitempty"`
}
