// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PrefetchI18n Fields for prefetching i18n strings/plurals.
//
// Object for passing i18n key values for prefetching of i18n strings and plurals in a spin response.
//
// swagger:model PrefetchI18n
type PrefetchI18n struct {

	// i18n plural string code for all paylines symbol payout message
	// Example: allpayline-win
	AllpaylinesMsg string `json:"allpaylines-msg,omitempty"`

	// the current currency
	// Example: GBP
	// Required: true
	Currency string `json:"currency"`

	// i18n plural string code for free spin count label
	// Example: free-counter
	FreeSpinsLabel string `json:"free-spins-label,omitempty"`

	// i18n plural string code for free spins won message
	// Example: won-amount-spins
	FreeSpinsMsg string `json:"free-spins-msg,omitempty"`

	// the current UI locale
	// Example: en-GB
	// Required: true
	Locale string `json:"locale"`

	// i18n plural string code for symbol payout message
	// Example: payout
	PayoutMsg string `json:"payout-msg,omitempty"`

	// i18n plural string code for total payout message
	// Example: game-pays
	TotalMsg string `json:"total-msg,omitempty"`
}
