// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoundStartResponse Round response.
//
// First result for playing a slots-machine round using the round, round/second, round/resume or round/debug API.
//
// swagger:model RoundStartResponse
type RoundStartResponse struct {

	// Details of the requested result (if it is not a spin).
	Data interface{} `json:"data,omitempty"`

	// round data
	// Required: true
	RoundData *RoundStartResponseRoundData `json:"roundData"`

	// Details of the requested result (if it is a spin).
	SpinData interface{} `json:"spinData,omitempty"`

	// Indicates if the request was successful.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
type RoundStartResponseRoundData struct {

	// Balance in cents after the spin.
	// Example: 1000
	// Required: true
	BalanceAfter int64 `json:"balanceAfter"`

	// Balance in cents before the spin.
	// Example: 1000
	// Required: true
	BalanceBefore int64 `json:"balanceBefore"`

	// Bet amount in cents.
	// Example: 1000
	// Required: true
	Bet int64 `json:"bet"`

	// Round result data kind.
	// Example: 1
	DataKind int64 `json:"dataKind,omitempty"`

	// Indicates that this spin result hit the max payout limit.
	// Example: 1
	MaxPayout int8 `json:"maxPayout,omitempty"`

	// Total number of results.
	// Example: 9
	// Required: true
	NrOfResults int64 `json:"nrOfResults"`

	// Indicates that the round requires a player choice before resuming.
	// Example: 1
	RequireChoice int8 `json:"requireChoice,omitempty"`

	// Round identification.
	// Example: uuid
	// Required: true
	RoundID string `json:"roundId"`

	// Round sequence number.
	// Example: 1
	// Required: true
	RoundSeq int64 `json:"roundSeq"`

	// Total win amount in cents from start of round.
	// Example: 11500
	// Required: true
	TotalWin int64 `json:"totalWin"`

	// Win amount in cents for this spin.
	// Example: 1000
	// Required: true
	Win int64 `json:"win"`
}
