// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoundFinishRequest Round finish request.
//
// Indicates that the slot-machine round has been completed in the FE.
//
// swagger:model RoundFinishRequest
type RoundFinishRequest struct {

	// Round identification.
	// Example: 5418324dc7884ad7b7d6e0fff31e4d1a
	// Required: true
	RoundID string `json:"roundId"`

	// Player session ID.
	// Example: bot9897cc03f5d7b43923a73bfaffc2d7dd43
	// Required: true
	SessionID string `json:"sessionId"`
}
