// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoundStartRequest Round start request.
//
// Start a slot-machine round, calculate all results (including free spins), and return the first spin.
//
// swagger:model RoundStartRequest
type RoundStartRequest struct {

	// Bet amount in cents.
	// Example: 1000
	// Required: true
	Bet int64 `json:"bet"`

	// i18n
	I18n *PrefetchI18n `json:"i18n,omitempty"`

	// Player session ID.
	// Example: bot9897cc03f5d7b43923a73bfaffc2d7dd43
	// Required: true
	SessionID string `json:"sessionId"`
}
