// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoundFinishResponse Round finish response.
//
// Response for successfully finishing a slot-machine round.
//
// swagger:model RoundFinishResponse
type RoundFinishResponse struct {

	// Indicates if the request was successful.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
