// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoundPaidRequest Round paid request.
//
// Start a slot-machine round, calculate all results forcing the requested bonus feature, and return the first spin.
//
// swagger:model RoundPaidRequest
type RoundPaidRequest struct {

	// Bet amount in cents.
	// Example: 1000
	// Required: true
	Bet int64 `json:"bet"`

	// Feature to be forced.
	// Example: 1
	// Required: true
	Feature int8 `json:"feature"`

	// i18n
	I18n *PrefetchI18n `json:"i18n,omitempty"`

	// Optional object with player choice(s).
	// Example: {"stickySymbol":5,"wing":"north"}
	PlayerChoice interface{} `json:"playerChoice,omitempty"`

	// Player session ID.
	// Example: bot9897cc03f5d7b43923a73bfaffc2d7dd43
	// Required: true
	SessionID string `json:"sessionId"`
}
