// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StringsRequest Get translation strings request.
//
// Request for retrieving translation strings.
//
// swagger:model StringsRequest
type StringsRequest struct {

	// Device identifier (1=mobile, 2=desktop).
	// Example: 1
	Device int8 `json:"device,omitempty"`

	// Translation string identifiers.
	// Example: ["button.ok","button.cancel"]
	// Required: true
	Identifiers []string `json:"identifiers"`

	// Locale for the translations.
	// Example: it-IT
	// Required: true
	Locale string `json:"locale"`
}
