// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// StringsResponse Get translation strings response.
//
// Response for retrieving the translation strings.
//
// swagger:model StringsResponse
type StringsResponse struct {

	// Translations.
	// Required: true
	Strings interface{} `json:"strings"`

	// Indicates if the request succeeded.
	// Example: true
	// Required: true
	Success bool `json:"success"`
}
