// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// GetSessionStateReader is a Reader for the GetSessionState structure.
type GetSessionStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSessionStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSessionStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSessionStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSessionStateOK creates a GetSessionStateOK with default headers values
func NewGetSessionStateOK() *GetSessionStateOK {
	return &GetSessionStateOK{}
}

/* GetSessionStateOK describes a response with status code 200, with default header values.

200
*/
type GetSessionStateOK struct {
	Payload *models.SessionStateResponse
}

func (o *GetSessionStateOK) Error() string {
	return fmt.Sprintf("[GET /session-state][%d] getSessionStateOK  %+v", 200, o.Payload)
}
func (o *GetSessionStateOK) GetPayload() *models.SessionStateResponse {
	return o.Payload
}

func (o *GetSessionStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSessionStateBadRequest creates a GetSessionStateBadRequest with default headers values
func NewGetSessionStateBadRequest() *GetSessionStateBadRequest {
	return &GetSessionStateBadRequest{}
}

/* GetSessionStateBadRequest describes a response with status code 400, with default header values.

400
*/
type GetSessionStateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetSessionStateBadRequest) Error() string {
	return fmt.Sprintf("[GET /session-state][%d] getSessionStateBadRequest  %+v", 400, o.Payload)
}
func (o *GetSessionStateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSessionStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSessionStateInternalServerError creates a GetSessionStateInternalServerError with default headers values
func NewGetSessionStateInternalServerError() *GetSessionStateInternalServerError {
	return &GetSessionStateInternalServerError{}
}

/* GetSessionStateInternalServerError describes a response with status code 500, with default header values.

500
*/
type GetSessionStateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetSessionStateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /session-state][%d] getSessionStateInternalServerError  %+v", 500, o.Payload)
}
func (o *GetSessionStateInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSessionStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
