// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlayerGameStateParams creates a new GetPlayerGameStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlayerGameStateParams() *GetPlayerGameStateParams {
	return &GetPlayerGameStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlayerGameStateParamsWithTimeout creates a new GetPlayerGameStateParams object
// with the ability to set a timeout on a request.
func NewGetPlayerGameStateParamsWithTimeout(timeout time.Duration) *GetPlayerGameStateParams {
	return &GetPlayerGameStateParams{
		timeout: timeout,
	}
}

// NewGetPlayerGameStateParamsWithContext creates a new GetPlayerGameStateParams object
// with the ability to set a context for a request.
func NewGetPlayerGameStateParamsWithContext(ctx context.Context) *GetPlayerGameStateParams {
	return &GetPlayerGameStateParams{
		Context: ctx,
	}
}

// NewGetPlayerGameStateParamsWithHTTPClient creates a new GetPlayerGameStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlayerGameStateParamsWithHTTPClient(client *http.Client) *GetPlayerGameStateParams {
	return &GetPlayerGameStateParams{
		HTTPClient: client,
	}
}

/* GetPlayerGameStateParams contains all the parameters to send to the API endpoint
   for the get player game state operation.

   Typically these are written to a http.Request.
*/
type GetPlayerGameStateParams struct {

	// XAPIKey.
	XAPIKey string

	// Session.
	Session string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get player game state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlayerGameStateParams) WithDefaults() *GetPlayerGameStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get player game state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlayerGameStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get player game state params
func (o *GetPlayerGameStateParams) WithTimeout(timeout time.Duration) *GetPlayerGameStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get player game state params
func (o *GetPlayerGameStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get player game state params
func (o *GetPlayerGameStateParams) WithContext(ctx context.Context) *GetPlayerGameStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get player game state params
func (o *GetPlayerGameStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get player game state params
func (o *GetPlayerGameStateParams) WithHTTPClient(client *http.Client) *GetPlayerGameStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get player game state params
func (o *GetPlayerGameStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the get player game state params
func (o *GetPlayerGameStateParams) WithXAPIKey(xAPIKey string) *GetPlayerGameStateParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the get player game state params
func (o *GetPlayerGameStateParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithSession adds the session to the get player game state params
func (o *GetPlayerGameStateParams) WithSession(session string) *GetPlayerGameStateParams {
	o.SetSession(session)
	return o
}

// SetSession adds the session to the get player game state params
func (o *GetPlayerGameStateParams) SetSession(session string) {
	o.Session = session
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlayerGameStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}

	// query param session
	qrSession := o.Session
	qSession := qrSession
	if qSession != "" {

		if err := r.SetQueryParam("session", qSession); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
