// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSessionStateParams creates a new GetSessionStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSessionStateParams() *GetSessionStateParams {
	return &GetSessionStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionStateParamsWithTimeout creates a new GetSessionStateParams object
// with the ability to set a timeout on a request.
func NewGetSessionStateParamsWithTimeout(timeout time.Duration) *GetSessionStateParams {
	return &GetSessionStateParams{
		timeout: timeout,
	}
}

// NewGetSessionStateParamsWithContext creates a new GetSessionStateParams object
// with the ability to set a context for a request.
func NewGetSessionStateParamsWithContext(ctx context.Context) *GetSessionStateParams {
	return &GetSessionStateParams{
		Context: ctx,
	}
}

// NewGetSessionStateParamsWithHTTPClient creates a new GetSessionStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSessionStateParamsWithHTTPClient(client *http.Client) *GetSessionStateParams {
	return &GetSessionStateParams{
		HTTPClient: client,
	}
}

/* GetSessionStateParams contains all the parameters to send to the API endpoint
   for the get session state operation.

   Typically these are written to a http.Request.
*/
type GetSessionStateParams struct {

	// XAPIKey.
	XAPIKey string

	// Session.
	Session string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get session state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionStateParams) WithDefaults() *GetSessionStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get session state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get session state params
func (o *GetSessionStateParams) WithTimeout(timeout time.Duration) *GetSessionStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session state params
func (o *GetSessionStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session state params
func (o *GetSessionStateParams) WithContext(ctx context.Context) *GetSessionStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session state params
func (o *GetSessionStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get session state params
func (o *GetSessionStateParams) WithHTTPClient(client *http.Client) *GetSessionStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get session state params
func (o *GetSessionStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the get session state params
func (o *GetSessionStateParams) WithXAPIKey(xAPIKey string) *GetSessionStateParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the get session state params
func (o *GetSessionStateParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithSession adds the session to the get session state params
func (o *GetSessionStateParams) WithSession(session string) *GetSessionStateParams {
	o.SetSession(session)
	return o
}

// SetSession adds the session to the get session state params
func (o *GetSessionStateParams) SetSession(session string) {
	o.Session = session
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}

	// query param session
	qrSession := o.Session
	qSession := qrSession
	if qSession != "" {

		if err := r.SetQueryParam("session", qSession); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
