// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGgSessionRoundsParams creates a new GetGgSessionRoundsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGgSessionRoundsParams() *GetGgSessionRoundsParams {
	return &GetGgSessionRoundsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGgSessionRoundsParamsWithTimeout creates a new GetGgSessionRoundsParams object
// with the ability to set a timeout on a request.
func NewGetGgSessionRoundsParamsWithTimeout(timeout time.Duration) *GetGgSessionRoundsParams {
	return &GetGgSessionRoundsParams{
		timeout: timeout,
	}
}

// NewGetGgSessionRoundsParamsWithContext creates a new GetGgSessionRoundsParams object
// with the ability to set a context for a request.
func NewGetGgSessionRoundsParamsWithContext(ctx context.Context) *GetGgSessionRoundsParams {
	return &GetGgSessionRoundsParams{
		Context: ctx,
	}
}

// NewGetGgSessionRoundsParamsWithHTTPClient creates a new GetGgSessionRoundsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGgSessionRoundsParamsWithHTTPClient(client *http.Client) *GetGgSessionRoundsParams {
	return &GetGgSessionRoundsParams{
		HTTPClient: client,
	}
}

/* GetGgSessionRoundsParams contains all the parameters to send to the API endpoint
   for the get gg session rounds operation.

   Typically these are written to a http.Request.
*/
type GetGgSessionRoundsParams struct {

	// XAPIKey.
	XAPIKey string

	// Session.
	Session string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get gg session rounds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGgSessionRoundsParams) WithDefaults() *GetGgSessionRoundsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get gg session rounds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGgSessionRoundsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get gg session rounds params
func (o *GetGgSessionRoundsParams) WithTimeout(timeout time.Duration) *GetGgSessionRoundsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get gg session rounds params
func (o *GetGgSessionRoundsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get gg session rounds params
func (o *GetGgSessionRoundsParams) WithContext(ctx context.Context) *GetGgSessionRoundsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get gg session rounds params
func (o *GetGgSessionRoundsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get gg session rounds params
func (o *GetGgSessionRoundsParams) WithHTTPClient(client *http.Client) *GetGgSessionRoundsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get gg session rounds params
func (o *GetGgSessionRoundsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the get gg session rounds params
func (o *GetGgSessionRoundsParams) WithXAPIKey(xAPIKey string) *GetGgSessionRoundsParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the get gg session rounds params
func (o *GetGgSessionRoundsParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithSession adds the session to the get gg session rounds params
func (o *GetGgSessionRoundsParams) WithSession(session string) *GetGgSessionRoundsParams {
	o.SetSession(session)
	return o
}

// SetSession adds the session to the get gg session rounds params
func (o *GetGgSessionRoundsParams) SetSession(session string) {
	o.Session = session
}

// WriteToRequest writes these params to a swagger request
func (o *GetGgSessionRoundsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}

	// query param session
	qrSession := o.Session
	qSession := qrSession
	if qSession != "" {

		if err := r.SetQueryParam("session", qSession); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
