// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoundStateParams creates a new GetRoundStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRoundStateParams() *GetRoundStateParams {
	return &GetRoundStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoundStateParamsWithTimeout creates a new GetRoundStateParams object
// with the ability to set a timeout on a request.
func NewGetRoundStateParamsWithTimeout(timeout time.Duration) *GetRoundStateParams {
	return &GetRoundStateParams{
		timeout: timeout,
	}
}

// NewGetRoundStateParamsWithContext creates a new GetRoundStateParams object
// with the ability to set a context for a request.
func NewGetRoundStateParamsWithContext(ctx context.Context) *GetRoundStateParams {
	return &GetRoundStateParams{
		Context: ctx,
	}
}

// NewGetRoundStateParamsWithHTTPClient creates a new GetRoundStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRoundStateParamsWithHTTPClient(client *http.Client) *GetRoundStateParams {
	return &GetRoundStateParams{
		HTTPClient: client,
	}
}

/* GetRoundStateParams contains all the parameters to send to the API endpoint
   for the get round state operation.

   Typically these are written to a http.Request.
*/
type GetRoundStateParams struct {

	// XAPIKey.
	XAPIKey string

	// Round.
	Round string

	// Session.
	Session string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get round state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoundStateParams) WithDefaults() *GetRoundStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get round state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoundStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get round state params
func (o *GetRoundStateParams) WithTimeout(timeout time.Duration) *GetRoundStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get round state params
func (o *GetRoundStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get round state params
func (o *GetRoundStateParams) WithContext(ctx context.Context) *GetRoundStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get round state params
func (o *GetRoundStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get round state params
func (o *GetRoundStateParams) WithHTTPClient(client *http.Client) *GetRoundStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get round state params
func (o *GetRoundStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the get round state params
func (o *GetRoundStateParams) WithXAPIKey(xAPIKey string) *GetRoundStateParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the get round state params
func (o *GetRoundStateParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithRound adds the round to the get round state params
func (o *GetRoundStateParams) WithRound(round string) *GetRoundStateParams {
	o.SetRound(round)
	return o
}

// SetRound adds the round to the get round state params
func (o *GetRoundStateParams) SetRound(round string) {
	o.Round = round
}

// WithSession adds the session to the get round state params
func (o *GetRoundStateParams) WithSession(session string) *GetRoundStateParams {
	o.SetSession(session)
	return o
}

// SetSession adds the session to the get round state params
func (o *GetRoundStateParams) SetSession(session string) {
	o.Session = session
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoundStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}

	// query param round
	qrRound := o.Round
	qRound := qrRound
	if qRound != "" {

		if err := r.SetQueryParam("round", qRound); err != nil {
			return err
		}
	}

	// query param session
	qrSession := o.Session
	qSession := qrSession
	if qSession != "" {

		if err := r.SetQueryParam("session", qSession); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
