// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// GetGgSessionRoundsReader is a Reader for the GetGgSessionRounds structure.
type GetGgSessionRoundsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGgSessionRoundsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGgSessionRoundsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGgSessionRoundsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGgSessionRoundsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetGgSessionRoundsOK creates a GetGgSessionRoundsOK with default headers values
func NewGetGgSessionRoundsOK() *GetGgSessionRoundsOK {
	return &GetGgSessionRoundsOK{}
}

/* GetGgSessionRoundsOK describes a response with status code 200, with default header values.

200
*/
type GetGgSessionRoundsOK struct {
	Payload *models.GGSessionRoundsResponse
}

func (o *GetGgSessionRoundsOK) Error() string {
	return fmt.Sprintf("[GET /gg/session-rounds][%d] getGgSessionRoundsOK  %+v", 200, o.Payload)
}
func (o *GetGgSessionRoundsOK) GetPayload() *models.GGSessionRoundsResponse {
	return o.Payload
}

func (o *GetGgSessionRoundsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GGSessionRoundsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGgSessionRoundsBadRequest creates a GetGgSessionRoundsBadRequest with default headers values
func NewGetGgSessionRoundsBadRequest() *GetGgSessionRoundsBadRequest {
	return &GetGgSessionRoundsBadRequest{}
}

/* GetGgSessionRoundsBadRequest describes a response with status code 400, with default header values.

400
*/
type GetGgSessionRoundsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetGgSessionRoundsBadRequest) Error() string {
	return fmt.Sprintf("[GET /gg/session-rounds][%d] getGgSessionRoundsBadRequest  %+v", 400, o.Payload)
}
func (o *GetGgSessionRoundsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetGgSessionRoundsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGgSessionRoundsInternalServerError creates a GetGgSessionRoundsInternalServerError with default headers values
func NewGetGgSessionRoundsInternalServerError() *GetGgSessionRoundsInternalServerError {
	return &GetGgSessionRoundsInternalServerError{}
}

/* GetGgSessionRoundsInternalServerError describes a response with status code 500, with default header values.

500
*/
type GetGgSessionRoundsInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetGgSessionRoundsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /gg/session-rounds][%d] getGgSessionRoundsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetGgSessionRoundsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetGgSessionRoundsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
