// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// OptionsAuthReader is a Reader for the OptionsAuth structure.
type OptionsAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionsAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionsAuthOK creates a OptionsAuthOK with default headers values
func NewOptionsAuthOK() *OptionsAuthOK {
	return &OptionsAuthOK{}
}

/* OptionsAuthOK describes a response with status code 200, with default header values.

200
*/
type OptionsAuthOK struct {
	Payload *models.CORSResponse
}

func (o *OptionsAuthOK) Error() string {
	return fmt.Sprintf("[OPTIONS /auth][%d] optionsAuthOK  %+v", 200, o.Payload)
}
func (o *OptionsAuthOK) GetPayload() *models.CORSResponse {
	return o.Payload
}

func (o *OptionsAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CORSResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
