// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsBoResetGameStateParams creates a new OptionsBoResetGameStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOptionsBoResetGameStateParams() *OptionsBoResetGameStateParams {
	return &OptionsBoResetGameStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsBoResetGameStateParamsWithTimeout creates a new OptionsBoResetGameStateParams object
// with the ability to set a timeout on a request.
func NewOptionsBoResetGameStateParamsWithTimeout(timeout time.Duration) *OptionsBoResetGameStateParams {
	return &OptionsBoResetGameStateParams{
		timeout: timeout,
	}
}

// NewOptionsBoResetGameStateParamsWithContext creates a new OptionsBoResetGameStateParams object
// with the ability to set a context for a request.
func NewOptionsBoResetGameStateParamsWithContext(ctx context.Context) *OptionsBoResetGameStateParams {
	return &OptionsBoResetGameStateParams{
		Context: ctx,
	}
}

// NewOptionsBoResetGameStateParamsWithHTTPClient creates a new OptionsBoResetGameStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewOptionsBoResetGameStateParamsWithHTTPClient(client *http.Client) *OptionsBoResetGameStateParams {
	return &OptionsBoResetGameStateParams{
		HTTPClient: client,
	}
}

/* OptionsBoResetGameStateParams contains all the parameters to send to the API endpoint
   for the options bo reset game state operation.

   Typically these are written to a http.Request.
*/
type OptionsBoResetGameStateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the options bo reset game state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoResetGameStateParams) WithDefaults() *OptionsBoResetGameStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the options bo reset game state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoResetGameStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) WithTimeout(timeout time.Duration) *OptionsBoResetGameStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) WithContext(ctx context.Context) *OptionsBoResetGameStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) WithHTTPClient(client *http.Client) *OptionsBoResetGameStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options bo reset game state params
func (o *OptionsBoResetGameStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsBoResetGameStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
