// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsGgPlayerRoundsParams creates a new OptionsGgPlayerRoundsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOptionsGgPlayerRoundsParams() *OptionsGgPlayerRoundsParams {
	return &OptionsGgPlayerRoundsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsGgPlayerRoundsParamsWithTimeout creates a new OptionsGgPlayerRoundsParams object
// with the ability to set a timeout on a request.
func NewOptionsGgPlayerRoundsParamsWithTimeout(timeout time.Duration) *OptionsGgPlayerRoundsParams {
	return &OptionsGgPlayerRoundsParams{
		timeout: timeout,
	}
}

// NewOptionsGgPlayerRoundsParamsWithContext creates a new OptionsGgPlayerRoundsParams object
// with the ability to set a context for a request.
func NewOptionsGgPlayerRoundsParamsWithContext(ctx context.Context) *OptionsGgPlayerRoundsParams {
	return &OptionsGgPlayerRoundsParams{
		Context: ctx,
	}
}

// NewOptionsGgPlayerRoundsParamsWithHTTPClient creates a new OptionsGgPlayerRoundsParams object
// with the ability to set a custom HTTPClient for a request.
func NewOptionsGgPlayerRoundsParamsWithHTTPClient(client *http.Client) *OptionsGgPlayerRoundsParams {
	return &OptionsGgPlayerRoundsParams{
		HTTPClient: client,
	}
}

/* OptionsGgPlayerRoundsParams contains all the parameters to send to the API endpoint
   for the options gg player rounds operation.

   Typically these are written to a http.Request.
*/
type OptionsGgPlayerRoundsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the options gg player rounds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsGgPlayerRoundsParams) WithDefaults() *OptionsGgPlayerRoundsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the options gg player rounds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsGgPlayerRoundsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) WithTimeout(timeout time.Duration) *OptionsGgPlayerRoundsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) WithContext(ctx context.Context) *OptionsGgPlayerRoundsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) WithHTTPClient(client *http.Client) *OptionsGgPlayerRoundsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options gg player rounds params
func (o *OptionsGgPlayerRoundsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsGgPlayerRoundsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
