// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsBoSessionsParams creates a new OptionsBoSessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOptionsBoSessionsParams() *OptionsBoSessionsParams {
	return &OptionsBoSessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsBoSessionsParamsWithTimeout creates a new OptionsBoSessionsParams object
// with the ability to set a timeout on a request.
func NewOptionsBoSessionsParamsWithTimeout(timeout time.Duration) *OptionsBoSessionsParams {
	return &OptionsBoSessionsParams{
		timeout: timeout,
	}
}

// NewOptionsBoSessionsParamsWithContext creates a new OptionsBoSessionsParams object
// with the ability to set a context for a request.
func NewOptionsBoSessionsParamsWithContext(ctx context.Context) *OptionsBoSessionsParams {
	return &OptionsBoSessionsParams{
		Context: ctx,
	}
}

// NewOptionsBoSessionsParamsWithHTTPClient creates a new OptionsBoSessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewOptionsBoSessionsParamsWithHTTPClient(client *http.Client) *OptionsBoSessionsParams {
	return &OptionsBoSessionsParams{
		HTTPClient: client,
	}
}

/* OptionsBoSessionsParams contains all the parameters to send to the API endpoint
   for the options bo sessions operation.

   Typically these are written to a http.Request.
*/
type OptionsBoSessionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the options bo sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoSessionsParams) WithDefaults() *OptionsBoSessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the options bo sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoSessionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the options bo sessions params
func (o *OptionsBoSessionsParams) WithTimeout(timeout time.Duration) *OptionsBoSessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options bo sessions params
func (o *OptionsBoSessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options bo sessions params
func (o *OptionsBoSessionsParams) WithContext(ctx context.Context) *OptionsBoSessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options bo sessions params
func (o *OptionsBoSessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options bo sessions params
func (o *OptionsBoSessionsParams) WithHTTPClient(client *http.Client) *OptionsBoSessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options bo sessions params
func (o *OptionsBoSessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsBoSessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
