// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsBoRoundParams creates a new OptionsBoRoundParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOptionsBoRoundParams() *OptionsBoRoundParams {
	return &OptionsBoRoundParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsBoRoundParamsWithTimeout creates a new OptionsBoRoundParams object
// with the ability to set a timeout on a request.
func NewOptionsBoRoundParamsWithTimeout(timeout time.Duration) *OptionsBoRoundParams {
	return &OptionsBoRoundParams{
		timeout: timeout,
	}
}

// NewOptionsBoRoundParamsWithContext creates a new OptionsBoRoundParams object
// with the ability to set a context for a request.
func NewOptionsBoRoundParamsWithContext(ctx context.Context) *OptionsBoRoundParams {
	return &OptionsBoRoundParams{
		Context: ctx,
	}
}

// NewOptionsBoRoundParamsWithHTTPClient creates a new OptionsBoRoundParams object
// with the ability to set a custom HTTPClient for a request.
func NewOptionsBoRoundParamsWithHTTPClient(client *http.Client) *OptionsBoRoundParams {
	return &OptionsBoRoundParams{
		HTTPClient: client,
	}
}

/* OptionsBoRoundParams contains all the parameters to send to the API endpoint
   for the options bo round operation.

   Typically these are written to a http.Request.
*/
type OptionsBoRoundParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the options bo round params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoRoundParams) WithDefaults() *OptionsBoRoundParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the options bo round params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsBoRoundParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the options bo round params
func (o *OptionsBoRoundParams) WithTimeout(timeout time.Duration) *OptionsBoRoundParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options bo round params
func (o *OptionsBoRoundParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options bo round params
func (o *OptionsBoRoundParams) WithContext(ctx context.Context) *OptionsBoRoundParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options bo round params
func (o *OptionsBoRoundParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options bo round params
func (o *OptionsBoRoundParams) WithHTTPClient(client *http.Client) *OptionsBoRoundParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options bo round params
func (o *OptionsBoRoundParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsBoRoundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
