// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// NewPostRoundNextParams creates a new PostRoundNextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRoundNextParams() *PostRoundNextParams {
	return &PostRoundNextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRoundNextParamsWithTimeout creates a new PostRoundNextParams object
// with the ability to set a timeout on a request.
func NewPostRoundNextParamsWithTimeout(timeout time.Duration) *PostRoundNextParams {
	return &PostRoundNextParams{
		timeout: timeout,
	}
}

// NewPostRoundNextParamsWithContext creates a new PostRoundNextParams object
// with the ability to set a context for a request.
func NewPostRoundNextParamsWithContext(ctx context.Context) *PostRoundNextParams {
	return &PostRoundNextParams{
		Context: ctx,
	}
}

// NewPostRoundNextParamsWithHTTPClient creates a new PostRoundNextParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRoundNextParamsWithHTTPClient(client *http.Client) *PostRoundNextParams {
	return &PostRoundNextParams{
		HTTPClient: client,
	}
}

/* PostRoundNextParams contains all the parameters to send to the API endpoint
   for the post round next operation.

   Typically these are written to a http.Request.
*/
type PostRoundNextParams struct {

	// XAPIKey.
	XAPIKey string

	// Payload.
	Payload *models.RoundNextRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post round next params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRoundNextParams) WithDefaults() *PostRoundNextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post round next params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRoundNextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post round next params
func (o *PostRoundNextParams) WithTimeout(timeout time.Duration) *PostRoundNextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post round next params
func (o *PostRoundNextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post round next params
func (o *PostRoundNextParams) WithContext(ctx context.Context) *PostRoundNextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post round next params
func (o *PostRoundNextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post round next params
func (o *PostRoundNextParams) WithHTTPClient(client *http.Client) *PostRoundNextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post round next params
func (o *PostRoundNextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the post round next params
func (o *PostRoundNextParams) WithXAPIKey(xAPIKey string) *PostRoundNextParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the post round next params
func (o *PostRoundNextParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithPayload adds the payload to the post round next params
func (o *PostRoundNextParams) WithPayload(payload *models.RoundNextRequest) *PostRoundNextParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post round next params
func (o *PostRoundNextParams) SetPayload(payload *models.RoundNextRequest) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PostRoundNextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
