// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostAuthReader is a Reader for the PostAuth structure.
type PostAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAuthOK creates a PostAuthOK with default headers values
func NewPostAuthOK() *PostAuthOK {
	return &PostAuthOK{}
}

/* PostAuthOK describes a response with status code 200, with default header values.

200
*/
type PostAuthOK struct {
	Payload *models.AuthenticationResponse
}

func (o *PostAuthOK) Error() string {
	return fmt.Sprintf("[POST /auth][%d] postAuthOK  %+v", 200, o.Payload)
}
func (o *PostAuthOK) GetPayload() *models.AuthenticationResponse {
	return o.Payload
}

func (o *PostAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthBadRequest creates a PostAuthBadRequest with default headers values
func NewPostAuthBadRequest() *PostAuthBadRequest {
	return &PostAuthBadRequest{}
}

/* PostAuthBadRequest describes a response with status code 400, with default header values.

400
*/
type PostAuthBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostAuthBadRequest) Error() string {
	return fmt.Sprintf("[POST /auth][%d] postAuthBadRequest  %+v", 400, o.Payload)
}
func (o *PostAuthBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostAuthBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthInternalServerError creates a PostAuthInternalServerError with default headers values
func NewPostAuthInternalServerError() *PostAuthInternalServerError {
	return &PostAuthInternalServerError{}
}

/* PostAuthInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostAuthInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostAuthInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth][%d] postAuthInternalServerError  %+v", 500, o.Payload)
}
func (o *PostAuthInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostAuthInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
