// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostRoundNextReader is a Reader for the PostRoundNext structure.
type PostRoundNextReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRoundNextReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRoundNextOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostRoundNextBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostRoundNextInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRoundNextOK creates a PostRoundNextOK with default headers values
func NewPostRoundNextOK() *PostRoundNextOK {
	return &PostRoundNextOK{}
}

/* PostRoundNextOK describes a response with status code 200, with default header values.

200
*/
type PostRoundNextOK struct {
	Payload *models.RoundNextResponse
}

func (o *PostRoundNextOK) Error() string {
	return fmt.Sprintf("[POST /round/next][%d] postRoundNextOK  %+v", 200, o.Payload)
}
func (o *PostRoundNextOK) GetPayload() *models.RoundNextResponse {
	return o.Payload
}

func (o *PostRoundNextOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoundNextResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoundNextBadRequest creates a PostRoundNextBadRequest with default headers values
func NewPostRoundNextBadRequest() *PostRoundNextBadRequest {
	return &PostRoundNextBadRequest{}
}

/* PostRoundNextBadRequest describes a response with status code 400, with default header values.

400
*/
type PostRoundNextBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostRoundNextBadRequest) Error() string {
	return fmt.Sprintf("[POST /round/next][%d] postRoundNextBadRequest  %+v", 400, o.Payload)
}
func (o *PostRoundNextBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostRoundNextBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoundNextInternalServerError creates a PostRoundNextInternalServerError with default headers values
func NewPostRoundNextInternalServerError() *PostRoundNextInternalServerError {
	return &PostRoundNextInternalServerError{}
}

/* PostRoundNextInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostRoundNextInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostRoundNextInternalServerError) Error() string {
	return fmt.Sprintf("[POST /round/next][%d] postRoundNextInternalServerError  %+v", 500, o.Payload)
}
func (o *PostRoundNextInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostRoundNextInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
