// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostComplexRoundWinReader is a Reader for the PostComplexRoundWin structure.
type PostComplexRoundWinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostComplexRoundWinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostComplexRoundWinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostComplexRoundWinBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostComplexRoundWinInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostComplexRoundWinOK creates a PostComplexRoundWinOK with default headers values
func NewPostComplexRoundWinOK() *PostComplexRoundWinOK {
	return &PostComplexRoundWinOK{}
}

/* PostComplexRoundWinOK describes a response with status code 200, with default header values.

200
*/
type PostComplexRoundWinOK struct {
	Payload *models.ComplexRoundWinResponse
}

func (o *PostComplexRoundWinOK) Error() string {
	return fmt.Sprintf("[POST /complex-round-win][%d] postComplexRoundWinOK  %+v", 200, o.Payload)
}
func (o *PostComplexRoundWinOK) GetPayload() *models.ComplexRoundWinResponse {
	return o.Payload
}

func (o *PostComplexRoundWinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComplexRoundWinResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundWinBadRequest creates a PostComplexRoundWinBadRequest with default headers values
func NewPostComplexRoundWinBadRequest() *PostComplexRoundWinBadRequest {
	return &PostComplexRoundWinBadRequest{}
}

/* PostComplexRoundWinBadRequest describes a response with status code 400, with default header values.

400
*/
type PostComplexRoundWinBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundWinBadRequest) Error() string {
	return fmt.Sprintf("[POST /complex-round-win][%d] postComplexRoundWinBadRequest  %+v", 400, o.Payload)
}
func (o *PostComplexRoundWinBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundWinBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundWinInternalServerError creates a PostComplexRoundWinInternalServerError with default headers values
func NewPostComplexRoundWinInternalServerError() *PostComplexRoundWinInternalServerError {
	return &PostComplexRoundWinInternalServerError{}
}

/* PostComplexRoundWinInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostComplexRoundWinInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundWinInternalServerError) Error() string {
	return fmt.Sprintf("[POST /complex-round-win][%d] postComplexRoundWinInternalServerError  %+v", 500, o.Payload)
}
func (o *PostComplexRoundWinInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundWinInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
