// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostComplexRoundInitReader is a Reader for the PostComplexRoundInit structure.
type PostComplexRoundInitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostComplexRoundInitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostComplexRoundInitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostComplexRoundInitBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostComplexRoundInitInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostComplexRoundInitOK creates a PostComplexRoundInitOK with default headers values
func NewPostComplexRoundInitOK() *PostComplexRoundInitOK {
	return &PostComplexRoundInitOK{}
}

/* PostComplexRoundInitOK describes a response with status code 200, with default header values.

200
*/
type PostComplexRoundInitOK struct {
	Payload *models.ComplexRoundInitResponse
}

func (o *PostComplexRoundInitOK) Error() string {
	return fmt.Sprintf("[POST /complex-round-init][%d] postComplexRoundInitOK  %+v", 200, o.Payload)
}
func (o *PostComplexRoundInitOK) GetPayload() *models.ComplexRoundInitResponse {
	return o.Payload
}

func (o *PostComplexRoundInitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComplexRoundInitResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundInitBadRequest creates a PostComplexRoundInitBadRequest with default headers values
func NewPostComplexRoundInitBadRequest() *PostComplexRoundInitBadRequest {
	return &PostComplexRoundInitBadRequest{}
}

/* PostComplexRoundInitBadRequest describes a response with status code 400, with default header values.

400
*/
type PostComplexRoundInitBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundInitBadRequest) Error() string {
	return fmt.Sprintf("[POST /complex-round-init][%d] postComplexRoundInitBadRequest  %+v", 400, o.Payload)
}
func (o *PostComplexRoundInitBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundInitBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundInitInternalServerError creates a PostComplexRoundInitInternalServerError with default headers values
func NewPostComplexRoundInitInternalServerError() *PostComplexRoundInitInternalServerError {
	return &PostComplexRoundInitInternalServerError{}
}

/* PostComplexRoundInitInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostComplexRoundInitInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundInitInternalServerError) Error() string {
	return fmt.Sprintf("[POST /complex-round-init][%d] postComplexRoundInitInternalServerError  %+v", 500, o.Payload)
}
func (o *PostComplexRoundInitInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundInitInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
