// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// NewPostComplexRoundInitParams creates a new PostComplexRoundInitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostComplexRoundInitParams() *PostComplexRoundInitParams {
	return &PostComplexRoundInitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostComplexRoundInitParamsWithTimeout creates a new PostComplexRoundInitParams object
// with the ability to set a timeout on a request.
func NewPostComplexRoundInitParamsWithTimeout(timeout time.Duration) *PostComplexRoundInitParams {
	return &PostComplexRoundInitParams{
		timeout: timeout,
	}
}

// NewPostComplexRoundInitParamsWithContext creates a new PostComplexRoundInitParams object
// with the ability to set a context for a request.
func NewPostComplexRoundInitParamsWithContext(ctx context.Context) *PostComplexRoundInitParams {
	return &PostComplexRoundInitParams{
		Context: ctx,
	}
}

// NewPostComplexRoundInitParamsWithHTTPClient creates a new PostComplexRoundInitParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostComplexRoundInitParamsWithHTTPClient(client *http.Client) *PostComplexRoundInitParams {
	return &PostComplexRoundInitParams{
		HTTPClient: client,
	}
}

/* PostComplexRoundInitParams contains all the parameters to send to the API endpoint
   for the post complex round init operation.

   Typically these are written to a http.Request.
*/
type PostComplexRoundInitParams struct {

	// XAPIKey.
	XAPIKey string

	// Payload.
	Payload *models.ComplexRoundInitRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post complex round init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostComplexRoundInitParams) WithDefaults() *PostComplexRoundInitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post complex round init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostComplexRoundInitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post complex round init params
func (o *PostComplexRoundInitParams) WithTimeout(timeout time.Duration) *PostComplexRoundInitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post complex round init params
func (o *PostComplexRoundInitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post complex round init params
func (o *PostComplexRoundInitParams) WithContext(ctx context.Context) *PostComplexRoundInitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post complex round init params
func (o *PostComplexRoundInitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post complex round init params
func (o *PostComplexRoundInitParams) WithHTTPClient(client *http.Client) *PostComplexRoundInitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post complex round init params
func (o *PostComplexRoundInitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the post complex round init params
func (o *PostComplexRoundInitParams) WithXAPIKey(xAPIKey string) *PostComplexRoundInitParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the post complex round init params
func (o *PostComplexRoundInitParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithPayload adds the payload to the post complex round init params
func (o *PostComplexRoundInitParams) WithPayload(payload *models.ComplexRoundInitRequest) *PostComplexRoundInitParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post complex round init params
func (o *PostComplexRoundInitParams) SetPayload(payload *models.ComplexRoundInitRequest) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PostComplexRoundInitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
