// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostComplexRoundBetReader is a Reader for the PostComplexRoundBet structure.
type PostComplexRoundBetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostComplexRoundBetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostComplexRoundBetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostComplexRoundBetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostComplexRoundBetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostComplexRoundBetOK creates a PostComplexRoundBetOK with default headers values
func NewPostComplexRoundBetOK() *PostComplexRoundBetOK {
	return &PostComplexRoundBetOK{}
}

/* PostComplexRoundBetOK describes a response with status code 200, with default header values.

200
*/
type PostComplexRoundBetOK struct {
	Payload *models.ComplexRoundBetResponse
}

func (o *PostComplexRoundBetOK) Error() string {
	return fmt.Sprintf("[POST /complex-round-bet][%d] postComplexRoundBetOK  %+v", 200, o.Payload)
}
func (o *PostComplexRoundBetOK) GetPayload() *models.ComplexRoundBetResponse {
	return o.Payload
}

func (o *PostComplexRoundBetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComplexRoundBetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundBetBadRequest creates a PostComplexRoundBetBadRequest with default headers values
func NewPostComplexRoundBetBadRequest() *PostComplexRoundBetBadRequest {
	return &PostComplexRoundBetBadRequest{}
}

/* PostComplexRoundBetBadRequest describes a response with status code 400, with default header values.

400
*/
type PostComplexRoundBetBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundBetBadRequest) Error() string {
	return fmt.Sprintf("[POST /complex-round-bet][%d] postComplexRoundBetBadRequest  %+v", 400, o.Payload)
}
func (o *PostComplexRoundBetBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundBetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundBetInternalServerError creates a PostComplexRoundBetInternalServerError with default headers values
func NewPostComplexRoundBetInternalServerError() *PostComplexRoundBetInternalServerError {
	return &PostComplexRoundBetInternalServerError{}
}

/* PostComplexRoundBetInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostComplexRoundBetInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundBetInternalServerError) Error() string {
	return fmt.Sprintf("[POST /complex-round-bet][%d] postComplexRoundBetInternalServerError  %+v", 500, o.Payload)
}
func (o *PostComplexRoundBetInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundBetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
