// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostComplexRoundCompleteReader is a Reader for the PostComplexRoundComplete structure.
type PostComplexRoundCompleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostComplexRoundCompleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostComplexRoundCompleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostComplexRoundCompleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostComplexRoundCompleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostComplexRoundCompleteOK creates a PostComplexRoundCompleteOK with default headers values
func NewPostComplexRoundCompleteOK() *PostComplexRoundCompleteOK {
	return &PostComplexRoundCompleteOK{}
}

/* PostComplexRoundCompleteOK describes a response with status code 200, with default header values.

200
*/
type PostComplexRoundCompleteOK struct {
	Payload *models.ComplexRoundCompleteResponse
}

func (o *PostComplexRoundCompleteOK) Error() string {
	return fmt.Sprintf("[POST /complex-round-complete][%d] postComplexRoundCompleteOK  %+v", 200, o.Payload)
}
func (o *PostComplexRoundCompleteOK) GetPayload() *models.ComplexRoundCompleteResponse {
	return o.Payload
}

func (o *PostComplexRoundCompleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComplexRoundCompleteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundCompleteBadRequest creates a PostComplexRoundCompleteBadRequest with default headers values
func NewPostComplexRoundCompleteBadRequest() *PostComplexRoundCompleteBadRequest {
	return &PostComplexRoundCompleteBadRequest{}
}

/* PostComplexRoundCompleteBadRequest describes a response with status code 400, with default header values.

400
*/
type PostComplexRoundCompleteBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundCompleteBadRequest) Error() string {
	return fmt.Sprintf("[POST /complex-round-complete][%d] postComplexRoundCompleteBadRequest  %+v", 400, o.Payload)
}
func (o *PostComplexRoundCompleteBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundCompleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostComplexRoundCompleteInternalServerError creates a PostComplexRoundCompleteInternalServerError with default headers values
func NewPostComplexRoundCompleteInternalServerError() *PostComplexRoundCompleteInternalServerError {
	return &PostComplexRoundCompleteInternalServerError{}
}

/* PostComplexRoundCompleteInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostComplexRoundCompleteInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostComplexRoundCompleteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /complex-round-complete][%d] postComplexRoundCompleteInternalServerError  %+v", 500, o.Payload)
}
func (o *PostComplexRoundCompleteInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostComplexRoundCompleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
