// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PostBoResetGameStateReader is a Reader for the PostBoResetGameState structure.
type PostBoResetGameStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBoResetGameStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostBoResetGameStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostBoResetGameStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostBoResetGameStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostBoResetGameStateOK creates a PostBoResetGameStateOK with default headers values
func NewPostBoResetGameStateOK() *PostBoResetGameStateOK {
	return &PostBoResetGameStateOK{}
}

/* PostBoResetGameStateOK describes a response with status code 200, with default header values.

200
*/
type PostBoResetGameStateOK struct {
	Payload *models.ResetGameStateResponse
}

func (o *PostBoResetGameStateOK) Error() string {
	return fmt.Sprintf("[POST /bo/reset-game-state][%d] postBoResetGameStateOK  %+v", 200, o.Payload)
}
func (o *PostBoResetGameStateOK) GetPayload() *models.ResetGameStateResponse {
	return o.Payload
}

func (o *PostBoResetGameStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResetGameStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostBoResetGameStateBadRequest creates a PostBoResetGameStateBadRequest with default headers values
func NewPostBoResetGameStateBadRequest() *PostBoResetGameStateBadRequest {
	return &PostBoResetGameStateBadRequest{}
}

/* PostBoResetGameStateBadRequest describes a response with status code 400, with default header values.

400
*/
type PostBoResetGameStateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PostBoResetGameStateBadRequest) Error() string {
	return fmt.Sprintf("[POST /bo/reset-game-state][%d] postBoResetGameStateBadRequest  %+v", 400, o.Payload)
}
func (o *PostBoResetGameStateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostBoResetGameStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostBoResetGameStateInternalServerError creates a PostBoResetGameStateInternalServerError with default headers values
func NewPostBoResetGameStateInternalServerError() *PostBoResetGameStateInternalServerError {
	return &PostBoResetGameStateInternalServerError{}
}

/* PostBoResetGameStateInternalServerError describes a response with status code 500, with default header values.

500
*/
type PostBoResetGameStateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostBoResetGameStateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /bo/reset-game-state][%d] postBoResetGameStateInternalServerError  %+v", 500, o.Payload)
}
func (o *PostBoResetGameStateInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostBoResetGameStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
