// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PutPlayerGameStateReader is a Reader for the PutPlayerGameState structure.
type PutPlayerGameStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPlayerGameStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutPlayerGameStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutPlayerGameStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutPlayerGameStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutPlayerGameStateOK creates a PutPlayerGameStateOK with default headers values
func NewPutPlayerGameStateOK() *PutPlayerGameStateOK {
	return &PutPlayerGameStateOK{}
}

/* PutPlayerGameStateOK describes a response with status code 200, with default header values.

200
*/
type PutPlayerGameStateOK struct {
	Payload *models.PutPlayerGameStateResponse
}

func (o *PutPlayerGameStateOK) Error() string {
	return fmt.Sprintf("[PUT /player-game-state][%d] putPlayerGameStateOK  %+v", 200, o.Payload)
}
func (o *PutPlayerGameStateOK) GetPayload() *models.PutPlayerGameStateResponse {
	return o.Payload
}

func (o *PutPlayerGameStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PutPlayerGameStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPlayerGameStateBadRequest creates a PutPlayerGameStateBadRequest with default headers values
func NewPutPlayerGameStateBadRequest() *PutPlayerGameStateBadRequest {
	return &PutPlayerGameStateBadRequest{}
}

/* PutPlayerGameStateBadRequest describes a response with status code 400, with default header values.

400
*/
type PutPlayerGameStateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutPlayerGameStateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /player-game-state][%d] putPlayerGameStateBadRequest  %+v", 400, o.Payload)
}
func (o *PutPlayerGameStateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutPlayerGameStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPlayerGameStateInternalServerError creates a PutPlayerGameStateInternalServerError with default headers values
func NewPutPlayerGameStateInternalServerError() *PutPlayerGameStateInternalServerError {
	return &PutPlayerGameStateInternalServerError{}
}

/* PutPlayerGameStateInternalServerError describes a response with status code 500, with default header values.

500
*/
type PutPlayerGameStateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PutPlayerGameStateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /player-game-state][%d] putPlayerGameStateInternalServerError  %+v", 500, o.Payload)
}
func (o *PutPlayerGameStateInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutPlayerGameStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
