// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// NewPutSessionStateParams creates a new PutSessionStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSessionStateParams() *PutSessionStateParams {
	return &PutSessionStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutSessionStateParamsWithTimeout creates a new PutSessionStateParams object
// with the ability to set a timeout on a request.
func NewPutSessionStateParamsWithTimeout(timeout time.Duration) *PutSessionStateParams {
	return &PutSessionStateParams{
		timeout: timeout,
	}
}

// NewPutSessionStateParamsWithContext creates a new PutSessionStateParams object
// with the ability to set a context for a request.
func NewPutSessionStateParamsWithContext(ctx context.Context) *PutSessionStateParams {
	return &PutSessionStateParams{
		Context: ctx,
	}
}

// NewPutSessionStateParamsWithHTTPClient creates a new PutSessionStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSessionStateParamsWithHTTPClient(client *http.Client) *PutSessionStateParams {
	return &PutSessionStateParams{
		HTTPClient: client,
	}
}

/* PutSessionStateParams contains all the parameters to send to the API endpoint
   for the put session state operation.

   Typically these are written to a http.Request.
*/
type PutSessionStateParams struct {

	// XAPIKey.
	XAPIKey string

	// Payload.
	Payload *models.PutSessionStateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put session state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSessionStateParams) WithDefaults() *PutSessionStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put session state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSessionStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put session state params
func (o *PutSessionStateParams) WithTimeout(timeout time.Duration) *PutSessionStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put session state params
func (o *PutSessionStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put session state params
func (o *PutSessionStateParams) WithContext(ctx context.Context) *PutSessionStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put session state params
func (o *PutSessionStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put session state params
func (o *PutSessionStateParams) WithHTTPClient(client *http.Client) *PutSessionStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put session state params
func (o *PutSessionStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAPIKey adds the xAPIKey to the put session state params
func (o *PutSessionStateParams) WithXAPIKey(xAPIKey string) *PutSessionStateParams {
	o.SetXAPIKey(xAPIKey)
	return o
}

// SetXAPIKey adds the xApiKey to the put session state params
func (o *PutSessionStateParams) SetXAPIKey(xAPIKey string) {
	o.XAPIKey = xAPIKey
}

// WithPayload adds the payload to the put session state params
func (o *PutSessionStateParams) WithPayload(payload *models.PutSessionStateRequest) *PutSessionStateParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the put session state params
func (o *PutSessionStateParams) SetPayload(payload *models.PutSessionStateRequest) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PutSessionStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-API-Key
	if err := r.SetHeaderParam("X-API-Key", o.XAPIKey); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
