// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PutSessionStateReader is a Reader for the PutSessionState structure.
type PutSessionStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSessionStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutSessionStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutSessionStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutSessionStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutSessionStateOK creates a PutSessionStateOK with default headers values
func NewPutSessionStateOK() *PutSessionStateOK {
	return &PutSessionStateOK{}
}

/* PutSessionStateOK describes a response with status code 200, with default header values.

200
*/
type PutSessionStateOK struct {
	Payload *models.PutSessionStateResponse
}

func (o *PutSessionStateOK) Error() string {
	return fmt.Sprintf("[PUT /session-state][%d] putSessionStateOK  %+v", 200, o.Payload)
}
func (o *PutSessionStateOK) GetPayload() *models.PutSessionStateResponse {
	return o.Payload
}

func (o *PutSessionStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PutSessionStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutSessionStateBadRequest creates a PutSessionStateBadRequest with default headers values
func NewPutSessionStateBadRequest() *PutSessionStateBadRequest {
	return &PutSessionStateBadRequest{}
}

/* PutSessionStateBadRequest describes a response with status code 400, with default header values.

400
*/
type PutSessionStateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutSessionStateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /session-state][%d] putSessionStateBadRequest  %+v", 400, o.Payload)
}
func (o *PutSessionStateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutSessionStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutSessionStateInternalServerError creates a PutSessionStateInternalServerError with default headers values
func NewPutSessionStateInternalServerError() *PutSessionStateInternalServerError {
	return &PutSessionStateInternalServerError{}
}

/* PutSessionStateInternalServerError describes a response with status code 500, with default header values.

500
*/
type PutSessionStateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PutSessionStateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /session-state][%d] putSessionStateInternalServerError  %+v", 500, o.Payload)
}
func (o *PutSessionStateInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutSessionStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
