// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"git-codecommit.eu-central-1.amazonaws.com/v1/repos/game-manager.git/dstore/models"
)

// PutPlayerGlobalStateReader is a Reader for the PutPlayerGlobalState structure.
type PutPlayerGlobalStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPlayerGlobalStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutPlayerGlobalStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutPlayerGlobalStateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutPlayerGlobalStateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutPlayerGlobalStateOK creates a PutPlayerGlobalStateOK with default headers values
func NewPutPlayerGlobalStateOK() *PutPlayerGlobalStateOK {
	return &PutPlayerGlobalStateOK{}
}

/* PutPlayerGlobalStateOK describes a response with status code 200, with default header values.

200
*/
type PutPlayerGlobalStateOK struct {
	Payload *models.PutPlayerGlobalStateResponse
}

func (o *PutPlayerGlobalStateOK) Error() string {
	return fmt.Sprintf("[PUT /player-global-state][%d] putPlayerGlobalStateOK  %+v", 200, o.Payload)
}
func (o *PutPlayerGlobalStateOK) GetPayload() *models.PutPlayerGlobalStateResponse {
	return o.Payload
}

func (o *PutPlayerGlobalStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PutPlayerGlobalStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPlayerGlobalStateBadRequest creates a PutPlayerGlobalStateBadRequest with default headers values
func NewPutPlayerGlobalStateBadRequest() *PutPlayerGlobalStateBadRequest {
	return &PutPlayerGlobalStateBadRequest{}
}

/* PutPlayerGlobalStateBadRequest describes a response with status code 400, with default header values.

400
*/
type PutPlayerGlobalStateBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *PutPlayerGlobalStateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /player-global-state][%d] putPlayerGlobalStateBadRequest  %+v", 400, o.Payload)
}
func (o *PutPlayerGlobalStateBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutPlayerGlobalStateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutPlayerGlobalStateInternalServerError creates a PutPlayerGlobalStateInternalServerError with default headers values
func NewPutPlayerGlobalStateInternalServerError() *PutPlayerGlobalStateInternalServerError {
	return &PutPlayerGlobalStateInternalServerError{}
}

/* PutPlayerGlobalStateInternalServerError describes a response with status code 500, with default header values.

500
*/
type PutPlayerGlobalStateInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PutPlayerGlobalStateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /player-global-state][%d] putPlayerGlobalStateInternalServerError  %+v", 500, o.Payload)
}
func (o *PutPlayerGlobalStateInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PutPlayerGlobalStateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
