package magic

const (
	KeyResultCountRange        = "result-count-range"
	KeyPlayerChoice            = "player-choice"
	KeySpinSymbolCount         = "spin-symbol-count"
	KeyAnySymbolCount          = "any-symbol-count"
	KeyTotalSymbolCount        = "total-symbol-count"
	KeySpinSymbolRange         = "spin-symbol-range"
	KeyAnySymbolRange          = "any-symbol-range"
	KeyTotalSymbolRange        = "total-symbol-range"
	KeySpinSymbolTypeCount     = "spin-symboltype-count"
	KeyAnySymbolTypeCount      = "any-symboltype-count"
	KeyTotalSymbolTypeCount    = "total-symboltype-count"
	KeySpinSymbolTypeRange     = "spin-symboltype-range"
	KeyAnySymbolTypeRange      = "any-symboltype-range"
	KeyTotalSymbolTypeRange    = "total-symboltype-range"
	KeySpinPaylinesRange       = "spin-paylines-range"
	KeyAnyPaylinesRange        = "any-paylines-range"
	KeySpinPayoutRange         = "spin-payout-range"
	KeyAnyPayoutRange          = "any-payout-range"
	KeyTotalPayoutRange        = "total-payout-range"
	KeySpinScatterPayouts      = "spin-scatter-payouts"
	KeyAnyScatterPayouts       = "any-scatter-payouts"
	KeySpinScatterPayout       = "spin-scatter-payout"
	KeyAnyScatterPayout        = "any-scatter-payout"
	KeySpinScatterPayoutSymbol = "spin-scatter-payout-symbol"
	KeyAnyScatterPayoutSymbol  = "any-scatter-payout-symbol"
	KeySpinClusterPayouts      = "spin-cluster-payouts"
	KeyAnyClusterPayouts       = "any-cluster-payouts"
	KeySpinClusterPayout       = "spin-cluster-payout"
	KeyAnyClusterPayout        = "any-cluster-payout"
	KeySpinClusterPayoutSymbol = "spin-cluster-payout-symbol"
	KeyAnyClusterPayoutSymbol  = "any-cluster-payout-symbol"
	KeyMaxPayout               = "max-payout"
	KeySpinPaylineCount        = "spin-payline-count"
	KeyAnyPaylineCount         = "any-payline-count"
	KeySpinPaylineSymbol       = "spin-payline-symbol"
	KeyAnyPaylineSymbol        = "any-payline-symbol"
	KeySpinStickyCount         = "spin-sticky-count"
	KeyAnyStickyCount          = "any-sticky-count"
	KeySpinStickySymbol        = "spin-sticky-symbol"
	KeyAnyStickySymbol         = "any-sticky-symbol"
	KeySpinStickyWild          = "spin-sticky-wild"
	KeyAnyStickyWild           = "any-sticky-wild"
	KeySpinMultiplierCount     = "spin-multiplier-count"
	KeyAnyMultiplierCount      = "any-multiplier-count"
	KeySpinMultiplierRange     = "spin-multiplier-range"
	KeyAnyMultiplierRange      = "any-multiplier-range"
	KeyLastMultiplierRange     = "last-multiplier-range"
	KeySpinMultiplierSymbol    = "spin-multiplier-symbol"
	KeyAnyMultiplierSymbol     = "any-multiplier-symbol"
	KeySpinMultiplierWild      = "spin-multiplier-wild"
	KeyAnyMultiplierWild       = "any-multiplier-wild"
	KeyRoundMultiplier         = "round-multiplier"
	KeyProgressMeter           = "progress-meter"
	KeySpinGrid                = "spin-grid"
	KeyAnyGrid                 = "any-grid"
)

const (
	fieldMin        = "min"
	fieldMax        = "max"
	fieldSymbol     = "symbol"
	fieldSymbolType = "type"
	fieldPayline    = "payline"
	fieldSeq        = "seq"
	fieldCount      = "count"
	fieldChoice     = "choice"
	fieldValue      = "value"
	fieldReels      = "reel..."
	fieldGrid       = "grid..."
)
