package consts

const (
	EnvDstoreHost         = "GS_DS_INTERNAL_HOST"
	EnvI18nHost           = "GS_IS_INTERNAL_HOST"
	EnvBBHost             = "GS_BB_INTERNAL_HOST"
	EnvMShost             = "GS_MS_HOST"
	EnvApiKey             = "GS_API_KEY"
	EnvDstoreApiKey       = "GS_DS_API_KEY"
	EnvBBkey              = "GS_BB_API_KEY"
	EnvMSkey              = "GS_MS_API_KEY"
	EnvSvcHost            = "GS_SVC_HOST"
	EnvSvcPort            = "GS_SVC_PORT"
	EnvEnvironment        = "GS_ENVIRONMENT"
	EnvCustomDNS          = "GS_CUSTOM_DNS"
	EnvRunEnv             = "GS_RUN_ENV"
	EnvConnCleanup        = "GS_CONN_CLEANUP"
	EnvLongPoll           = "GS_LONG_POLL_TIMEOUT"
	EnvMsgBrokers         = "GS_RP_IPS"
	EnvEventsTopic        = "GS_RP_TOPIC_EVENTS"
	EnvMessagesTopic      = "GS_RP_TOPIC_MESSAGES"
	EnvHashesTopic        = "GS_RP_TOPIC_HASHES"
	EnvResolveProtocol    = "GS_RESOLVE_PROTOCOL"
	EnvResolveTimeout     = "GS_RESOLVE_TIMEOUT"
	EnvDnsCacheRefresh    = "GS_DNS_CACHE_REFRESH"
	EnvClientTimeout      = "GS_CLIENT_TIMEOUT"
	EnvMaxClientConn      = "GS_MAX_CLIENT_CONN"
	EnvClientRetries      = "GS_CLIENT_RETRIES"
	EnvClientRetryBackoff = "GS_CLIENT_RETRY_BACKOFF"
	EnvSessionMetrics     = "GS_SESSION_METRICS"
	EnvNoDefaultHeaders   = "GS_HTTP_NO_DEFAULT_HEADERS"
	EnvNoCors             = "GS_HTTP_NO_CORS"
	EnvNoCompression      = "GS_HTTP_NO_COMPRESS"

	ValueDev  = "DEV"
	ValueTrue = "1"
)
