// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthenticationResponse AuthenticationResponse
//
// swagger:model AuthenticationResponse
type AuthenticationResponse struct {

	// player data
	// Required: true
	PlayerData *Player `json:"playerData"`

	// Player session ID
	// Example: bot9897cc03f5d7b43923a73bfaffc2d7dd43
	// Required: true
	SessionID string `json:"sessionId"`

	// Boolean determining whether the request was successful
	// Example: true
	// Required: true
	Success bool `json:"success"`
}

// Validate validates this authentication response
func (m *AuthenticationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlayerData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthenticationResponse) validatePlayerData(formats strfmt.Registry) error {

	if err := validate.Required("playerData", "body", m.PlayerData); err != nil {
		return err
	}

	if m.PlayerData != nil {
		if err := m.PlayerData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

func (m *AuthenticationResponse) validateSessionID(formats strfmt.Registry) error {

	if err := validate.RequiredString("sessionId", "body", m.SessionID); err != nil {
		return err
	}

	return nil
}

func (m *AuthenticationResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", bool(m.Success)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this authentication response based on the context it is used
func (m *AuthenticationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlayerData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthenticationResponse) contextValidatePlayerData(ctx context.Context, formats strfmt.Registry) error {

	if m.PlayerData != nil {
		if err := m.PlayerData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthenticationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthenticationResponse) UnmarshalBinary(b []byte) error {
	var res AuthenticationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
