// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BORoundDataResponse BORoundDataResponse
//
// swagger:model BORoundDataResponse
type BORoundDataResponse struct {

	// Currency
	// Example: EUR
	// Required: true
	Currency string `json:"currency"`

	// New balance in cents
	// Example: 100000
	// Required: true
	NewBalance int64 `json:"newBalance"`

	// Round result JSON
	// Example: {}
	// Required: true
	Result string `json:"result"`

	// Boolean determining whether the request was successful
	// Example: true
	// Required: true
	Success bool `json:"success"`
}

// Validate validates this b o round data response
func (m *BORoundDataResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNewBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BORoundDataResponse) validateCurrency(formats strfmt.Registry) error {

	if err := validate.RequiredString("currency", "body", m.Currency); err != nil {
		return err
	}

	return nil
}

func (m *BORoundDataResponse) validateNewBalance(formats strfmt.Registry) error {

	if err := validate.Required("newBalance", "body", int64(m.NewBalance)); err != nil {
		return err
	}

	return nil
}

func (m *BORoundDataResponse) validateResult(formats strfmt.Registry) error {

	if err := validate.RequiredString("result", "body", m.Result); err != nil {
		return err
	}

	return nil
}

func (m *BORoundDataResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", bool(m.Success)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this b o round data response based on context it is used
func (m *BORoundDataResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BORoundDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BORoundDataResponse) UnmarshalBinary(b []byte) error {
	var res BORoundDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
