// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ComplexRoundInitResponse ComplexRoundInitResponse
//
// swagger:model ComplexRoundInitResponse
type ComplexRoundInitResponse struct {

	// player data
	// Required: true
	PlayerData *ComplexRoundInitResponsePlayerData `json:"playerData"`

	// Round ID
	// Example: 7sKCVTqlnw9sRV858GFbINXotSoSCZrK
	// Required: true
	RoundID string `json:"roundId"`

	// Boolean determining whether the request was successful
	// Example: true
	// Required: true
	Success bool `json:"success"`
}

// Validate validates this complex round init response
func (m *ComplexRoundInitResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlayerData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoundID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplexRoundInitResponse) validatePlayerData(formats strfmt.Registry) error {

	if err := validate.Required("playerData", "body", m.PlayerData); err != nil {
		return err
	}

	if m.PlayerData != nil {
		if err := m.PlayerData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

func (m *ComplexRoundInitResponse) validateRoundID(formats strfmt.Registry) error {

	if err := validate.RequiredString("roundId", "body", m.RoundID); err != nil {
		return err
	}

	return nil
}

func (m *ComplexRoundInitResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", bool(m.Success)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this complex round init response based on the context it is used
func (m *ComplexRoundInitResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlayerData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplexRoundInitResponse) contextValidatePlayerData(ctx context.Context, formats strfmt.Registry) error {

	if m.PlayerData != nil {
		if err := m.PlayerData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComplexRoundInitResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplexRoundInitResponse) UnmarshalBinary(b []byte) error {
	var res ComplexRoundInitResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ComplexRoundInitResponsePlayerData complex round init response player data
//
// swagger:model ComplexRoundInitResponsePlayerData
type ComplexRoundInitResponsePlayerData struct {

	// Updated player balance in cents
	// Example: 999000
	// Required: true
	Balance int64 `json:"balance"`
}

// Validate validates this complex round init response player data
func (m *ComplexRoundInitResponsePlayerData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComplexRoundInitResponsePlayerData) validateBalance(formats strfmt.Registry) error {

	if err := validate.Required("playerData"+"."+"balance", "body", int64(m.Balance)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this complex round init response player data based on context it is used
func (m *ComplexRoundInitResponsePlayerData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComplexRoundInitResponsePlayerData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComplexRoundInitResponsePlayerData) UnmarshalBinary(b []byte) error {
	var res ComplexRoundInitResponsePlayerData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
