// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Player Player
//
// swagger:model Player
type Player struct {

	// Player balance in cents
	// Example: 10000
	// Required: true
	Balance int64 `json:"balance"`

	// Currency
	// Example: EUR
	// Required: true
	Currency string `json:"currency"`

	// Player nickname
	// Example: john
	Nickname string `json:"nickname,omitempty"`

	// Player ID
	// Example: player-1234
	// Required: true
	PlayerID string `json:"playerId"`
}

// Validate validates this player
func (m *Player) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlayerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Player) validateBalance(formats strfmt.Registry) error {

	if err := validate.Required("balance", "body", int64(m.Balance)); err != nil {
		return err
	}

	return nil
}

func (m *Player) validateCurrency(formats strfmt.Registry) error {

	if err := validate.RequiredString("currency", "body", m.Currency); err != nil {
		return err
	}

	return nil
}

func (m *Player) validatePlayerID(formats strfmt.Registry) error {

	if err := validate.RequiredString("playerId", "body", m.PlayerID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this player based on context it is used
func (m *Player) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Player) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Player) UnmarshalBinary(b []byte) error {
	var res Player
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
