// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlayerGameStateResponse PlayerGameStateResponse
//
// swagger:model PlayerGameStateResponse
type PlayerGameStateResponse struct {

	// Casino ID
	// Example: casino-1234
	// Required: true
	CasinoID string `json:"casinoId"`

	// Player ID
	// Example: player-1234
	// Required: true
	PlayerID string `json:"playerId"`

	// Player game state JSON
	// Example: {}
	// Required: true
	State string `json:"state"`
}

// Validate validates this player game state response
func (m *PlayerGameStateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCasinoID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlayerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlayerGameStateResponse) validateCasinoID(formats strfmt.Registry) error {

	if err := validate.RequiredString("casinoId", "body", m.CasinoID); err != nil {
		return err
	}

	return nil
}

func (m *PlayerGameStateResponse) validatePlayerID(formats strfmt.Registry) error {

	if err := validate.RequiredString("playerId", "body", m.PlayerID); err != nil {
		return err
	}

	return nil
}

func (m *PlayerGameStateResponse) validateState(formats strfmt.Registry) error {

	if err := validate.RequiredString("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this player game state response based on context it is used
func (m *PlayerGameStateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerGameStateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerGameStateResponse) UnmarshalBinary(b []byte) error {
	var res PlayerGameStateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
