// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RoundResponse RoundResponse
//
// swagger:model RoundResponse
type RoundResponse struct {

	// player data
	// Required: true
	PlayerData *RoundResponsePlayerData `json:"playerData"`

	// Round ID
	// Example: 7sKCVTqlnw9sRV858GFbINXotSoSCZrK
	// Required: true
	RoundID string `json:"roundId"`

	// Boolean determining whether the request was successful
	// Example: true
	// Required: true
	Success bool `json:"success"`
}

// Validate validates this round response
func (m *RoundResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlayerData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoundID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoundResponse) validatePlayerData(formats strfmt.Registry) error {

	if err := validate.Required("playerData", "body", m.PlayerData); err != nil {
		return err
	}

	if m.PlayerData != nil {
		if err := m.PlayerData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

func (m *RoundResponse) validateRoundID(formats strfmt.Registry) error {

	if err := validate.RequiredString("roundId", "body", m.RoundID); err != nil {
		return err
	}

	return nil
}

func (m *RoundResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", bool(m.Success)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this round response based on the context it is used
func (m *RoundResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlayerData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoundResponse) contextValidatePlayerData(ctx context.Context, formats strfmt.Registry) error {

	if m.PlayerData != nil {
		if err := m.PlayerData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playerData")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playerData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RoundResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoundResponse) UnmarshalBinary(b []byte) error {
	var res RoundResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RoundResponsePlayerData round response player data
//
// swagger:model RoundResponsePlayerData
type RoundResponsePlayerData struct {

	// Updated player balance in cents
	// Example: 999000
	// Required: true
	Balance int64 `json:"balance"`
}

// Validate validates this round response player data
func (m *RoundResponsePlayerData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoundResponsePlayerData) validateBalance(formats strfmt.Registry) error {

	if err := validate.Required("playerData"+"."+"balance", "body", int64(m.Balance)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this round response player data based on context it is used
func (m *RoundResponsePlayerData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoundResponsePlayerData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoundResponsePlayerData) UnmarshalBinary(b []byte) error {
	var res RoundResponsePlayerData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
